### ISSUE TITLE
Creating OS X Agent Installer on Ubuntu 14.04

### ISSUE THREAD

**Issue by kdm2730** [mozilla/mig#218]
Hello,

I have been working with Ubuntu 14.04 and was able to create functioning agent installers for Linux and Windows after setting up everything for MIG.  Creating an agent for darwin is giving me some problems.  The command that I am running is: make CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 mig-agent BUILDENV=prod OS=darwin

> 
root@ubuntu:/go/src/mig.ninja/mig#` make CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 mig-agent BUILDENV=prod OS=darwin
mkdir -p bin/darwin/amd64
echo building mig-agent for darwin/amd64
building mig-agent for darwin/amd64
if [ ! -r conf/mig-agent-conf.go.inc ]; then echo "conf/mig-agent-conf.go.inc configuration file does not exist" ; exit 1; fi
test if the agent configuration variable contains something different than the default value
and if so, replace the link to the default configuration with the provided configuration
if [ conf/mig-agent-conf.go.inc != "conf/mig-agent-conf.go.inc" ]; then rm mig-agent/configuration.go; cp conf/mig-agent-conf.go.inc mig-agent/configuration.go; fi
GOOS=darwin GOARCH=amd64 GO15VENDOREXPERIMENT=1 go build  -o bin/darwin/amd64/mig-agent-20160427-0.f0cd2c6.prod"" -ldflags "-X mig.ninja/mig.Version=20160427-0.f0cd2c6.prod" mig.ninja/mig/mig-agent
runtime/cgo
/tmp/go-build061453245/runtime/cgo/_obj/_cgo_main.c:1:0: error: -fPIC ignored for target (all code is position independent) [-Werror]
 int main() { return 0; }
 ^
cc1: all warnings being treated as errors
make: *** [mig-agent] Error 2

> 

Any assistance would be greatly appreciated.

Thanks,
Kyle
